baseURL = '/'
languageCode = 'en-us'
title = 'francisco.altoe.com.ar'
theme = 'hugo-cat'

[params]
ava = 'img/avatar.png'
owner = 'Francisco Altoe'
talk = "Hello world! <br> My name is Francisco. I'm a full stack developer from Argentina ğŸ‡¦ğŸ‡· <br> My preferred web stack is Django ğŸ + React âš›ï¸ <br> Find out about my socials, professional experience and open source projects below:"
blogSection = ['blog']
description = 'Francisco Altoe'

# TODO: uncomment when more pages are added

#[[menu.main]]
#name = 'Home'
#url = '/'
#weight = 1

#[[menu.main]]
#name = 'Blog'
#url = '/blog/'
#weight = 2
